# ===================================================================
# CONFIGURACIÓN GENERAL DEL MICROSERVICIO
# ===================================================================
server.port=8099
spring.application.name=ventas-service

# ===================================================================
# CONEXIÓN A BASE DE DATOS (ORACLE XE LOCAL)
# ===================================================================
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XEPDB1
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# IMPORTANTE: Aquí usas SYSTEM y la contraseña que inventes en el asistente de instalación
spring.datasource.username=SYSTEM
spring.datasource.password=tonsoffun4ever9.

# ===================================================================
# CONFIGURACIÓN DE JPA / HIBERNATE (CORRECCIÓN DE ERRORES)
# ===================================================================
# Soluciona el error 'Unable to determine Dialect' indicando que el motor es Oracle
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

# Genera o actualiza la tabla "ventas" automáticamente en tu base de datos al dar Play
spring.jpa.hibernate.ddl-auto=update

# Muestra en la consola las consultas internas que hace Spring para que verifiques que funciona
spring.jpa.show-sql=true

# ===================================================================
# INTEGRACIÓN CON LA INFRAESTRUCTURA DE MICROSERVICIOS
# ===================================================================
# Mantenemos tu conexión a la torre de control de Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/