spring.application.name=produccion
server.port=8083

spring.flyway.enabled=false

#Oracle Connection con Wallet
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@clases_high?TNS_ADMIN=C:/OracleWallet
spring.datasource.username=ADMIN
spring.datasource.password=Pabloneruda#334

#CONFIGURACIÓN CRÍTICA: Limitar el Pool para el Free Tier
#Con esto evitamos el ORA-12523
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.max-lifetime=1800000

#JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
#Eliminamos la línea del dialecto manual, Spring Boot 3+ lo detecta solo y evita conflictos
spring.jpa.open-in-view=false

#Eureka Client
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html