spring.application.name=LoginAuth

server.port=8081

# configuracion de eureka
eureka.client.service-url.defaultZone=${EUR_SERVER:http://localhost:8761/eureka/}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# --- NUEVA CONFIGURACION ORACLE CLOUD ---
spring.datasource.url=jdbc:oracle:thin:@clases_high?TNS_ADMIN=/app/OracleWallet
spring.datasource.username=ADMIN
spring.datasource.password=Pabloneruda#334
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.flyway.baseline-on-migrate=true
# Forzar a Flyway a usar la misma ruta de la Wallet de Docker
spring.flyway.url=jdbc:oracle:thin:@clases_high?TNS_ADMIN=/app/OracleWallet
spring.flyway.user=ADMIN
spring.flyway.password=Pabloneruda#334

# CONFIGURACIÓN CRÍTICA: Limitar el Pool para el Free Tier de Oracle
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.max-lifetime=1800000